mysql.database.driver: "com.mysql.jdbc.Driver"
mysql.database.url: "jdbc:mysql://127.0.0.1:3306/mytest"

vault.url: "http://127.0.0.1:8200"
vault.mysql.rolename: "allrole"

vault.sampleapp.roleId: "d5f7f0d9-29b6-dddd-1c96-6b6f34402c1e"
vault.sampleapp.secretId: "b54f8008-cc85-4073-3442-3c7a48614b17"
spring.zipkin.baseurl: http://localhost:9411

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
spring.cloud.config.name: zipkin
spring.cloud.config.discovery.service-id: config
spring.cloud.config.discovery.enabled: true
spring.cloud.config.username: configUser
spring.cloud.config.password: configPassword


database:
    entities: "com.aravind.sample.entity.User"
    User: id,name,desc
    UserTbl:
        id: mysql
        name: postgresql
        desc: mongodb
    priority: mysql,postgre,mongodb