tracer.property: "I am default"
postgre.database.username: "aravindviswanathan"
postgre.database.password: "MyNewPass"
postgre.database.driver: "org.postgresql.Driver"
postgre.database.url: "jdbc:postgresql://127.0.0.1:5432/mytest"

mysql.database.username: "aravind"
mysql.database.password: "MyNewPass"
mysql.database.driver: "com.mysql.jdbc.Driver"
mysql.database.url: "jdbc:mysql://127.0.0.1:3306/mytest"


user:
     userId: mysql
     id: mysql
     name: postgresql
     desc: mongodb