server:
       port: 8888
spring:
       profiles: 
                active: native
       cloud: 
             config:
                    server:
                           native:
                                  searchLocations: file:///Users/aravindviswanathan/Aravind/Development/workspaces/confsvr/src/main/resources/config/samples       