tracer.property: "I am default"
postgre.database.username: "aravindviswanathan"
postgre.database.password: "MyNewPass"
postgre.database.driver: "org.postgresql.Driver"
postgre.database.url: "jdbc:postgresql://127.0.0.1:5432/mytest"

mysql.database.username: "aravind"
mysql.database.password: "MyNewPass"
mysql.database.driver: "com.mysql.jdbc.Driver"
mysql.database.url: "jdbc:mysql://127.0.0.1:3306/mytest"

vault.sampleapp.roleId: "de4c8ce0-fd7f-117f-13ee-ea7cf1609315"
vault.sampleapp.secretId: "07f467c5-09ec-97c1-6a91-92d1c0f403e3"
vault.url: "http://127.0.0.1:8200"

user:
     userId: mysql
     id: mysql
     name: postgresql
     desc: mongodb